services:
  db:
    image: postgres:14
    container_name: yimanbek_db
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/

  web:
    build: 
      context: .
      dockerfile: ./docker/dockerfile.local
    depends_on:
      db:
        condition: service_healthy
    container_name: django_devops_lab-WEB
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A django_devops_lab worker -l INFO
    volumes: 
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER=amqp://admin:admin@rabbitmq:5672//
      - CELERY_BACKEND=amqp://admin:admin@rabbitmq:5672//
    depends_on:
      - web
      - rabbitmq

  rabbitmq: 
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_beat:
    build: .
    container_name: celery-beat
    command: celery -A django_devops_lab beat -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - rabbitmq

  celery_flower:
    build: .
    command: celery -A django_devops_lab flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - web
      - rabbitmq
    volumes:
      - .:/usr/src/app/

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    restart: always
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"

volumes:
  pg_data:
  static_volume:
  media_volume: